services:
  docs:
    image: python:3.13.0-alpine@sha256:d4daf858ce04f8e6f9a3f73d036f7a8dbb3b9541dccdb87e93993589449c5b9e
    entrypoint: [ ]
    command: sh -c "cd docs && pip install -r requirements.txt && mkdocs serve --dev-addr=0.0.0.0:8000"
    volumes:
      - .:/docs
    ports:
      - 8000:8000
