services:
  docs:
    image: python:3.13.1-alpine@sha256:b6f01a01e34091438a29b6dda4664199e34731fb2581ebb6fe255a2ebf441099
    entrypoint: [ ]
    command: sh -c "cd docs && pip install -r requirements.txt && mkdocs serve --dev-addr=0.0.0.0:8000"
    volumes:
      - .:/docs
    ports:
      - 8000:8000
